# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_date',
            field=models.DateField(),
        ),
    ]
