# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20170905_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='profit_in_ticks',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='profit_in_ticks',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
