# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-02 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_account_euro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='euro',
            new_name='cash',
        ),
    ]
