# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-06 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20170706_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='estimated_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
