# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_auto_20170707_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='equity',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_date',
            field=models.DateTimeField(),
        ),
    ]
