# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-07 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20170707_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equity',
        ),
    ]
