# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_equity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exit',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Entry'),
        ),
        migrations.AlterField(
            model_name='exit',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.Game'),
        ),
    ]
