# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_auto_20170709_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
