# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_entry_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='profit_to_risk',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
