# Generated by Django 2.0.1 on 2018-01-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_game_profit_to_risk'),
        ('trading', '0003_auto_20170907_1218'),
    ]

    operations = [
    ]
