# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_merge_20180103_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exit',
            name='profit_in_ticks',
        ),
        migrations.RemoveField(
            model_name='game',
            name='profit_in_ticks',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='exit',
            name='exit_date',
            field=models.DateTimeField(),
        ),
    ]
